Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: HelloWorldController.helloWorld
      Runtime: nodejs18.x

  MyIAMUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: ManageHelloWorldFunction
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:*
                Resource: !GetAtt HelloWorldFunction.Arn