name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: 
      image: amazon/aws-sam-cli-build-image-nodejs18.x
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Package AWS SAM application
      run: sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket cicd-bucket2 --region $AWS_REGION

    - name: Deploy AWS SAM application
      run: sam deploy --template-file packaged.yaml --stack-name cicd-stack --capabilities CAPABILITY_IAM --region $AWS_REGION
      